In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv('/content/chi_square_large_data_science.csv')
df

Gender         Specialization
0     Other  Business_Intelligence
1      Male  Business_Intelligence
2     Other  Business_Intelligence
3     Other  Business_Intelligence
4      Male         Data_Analytics
..      ...                    ...
995  Female       Machine_Learning
996  Female       Data_Engineering
997   Other  Business_Intelligence
998   Other       Machine_Learning
999    Male       Machine_Learning

[1000 rows x 2 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   Gender          1000 non-null   object
 1   Specialization  1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB


In [5]:
df.columns

Index(['Gender', 'Specialization'], dtype='object')

In [6]:
df.describe()

Gender    Specialization
count    1000              1000
unique      3                 4
top      Male  Machine_Learning
freq      355               267

In [7]:
df.isnull().sum()

Gender            0
Specialization    0
dtype: int64

In [10]:
#contingency_table
contingency_table = pd.crosstab(df['Gender'], df['Specialization'])
contingency_table


Specialization  Business_Intelligence  Data_Analytics  Data_Engineering  \
Gender                                                                    
Female                             91              60                78   
Male                               95              80                93   
Other                              74              82                80   

Specialization  Machine_Learning  
Gender                            
Female                        97  
Male                          87  
Other                         83

In [11]:
df.Gender.unique()

array(['Other', 'Male', 'Female'], dtype=object)

In [16]:
# Perform the chi-square test
from scipy.stats import chi2_contingency
chi2, p, dof, expected = chi2_contingency(contingency_table)
chi2, p, dof, expected


(7.583876616607104,
 0.27020126511822495,
 6,
 array([[84.76 , 72.372, 81.826, 87.042],
        [92.3  , 78.81 , 89.105, 94.785],
        [82.94 , 70.818, 80.069, 85.173]]))

In [19]:
# Print the results
print(f"Chi-square statistic: {chi2}")
print(f"P-value: {p}")
print(f"Degrees of freedom: {dof}")
print("Expected frequencies:/n", expected)
print(contingency_table)
print(f"P-value: {p}")


Chi-square statistic: 7.583876616607104
P-value: 0.27020126511822495
Degrees of freedom: 6
Expected frequencies:/n [[84.76  72.372 81.826 87.042]
 [92.3   78.81  89.105 94.785]
 [82.94  70.818 80.069 85.173]]
Specialization  Business_Intelligence  Data_Analytics  Data_Engineering  \
Gender                                                                    
Female                             91              60                78   
Male                               95              80                93   
Other                              74              82                80   

Specialization  Machine_Learning  
Gender                            
Female                        97  
Male                          87  
Other                         83  
P-value: 0.27020126511822495


In [20]:
# Interpret the result
alpha = 0.05
if p < alpha:
    print("There is a significant association between Gender and Specialization.")
else:
    print("There is no significant association between Gender and Specialization.")

There is no significant association between Gender and Specialization.


In [21]:
df1=pd.read_csv('/content/chi_square_large_product_satisfaction.csv')
df1

Product_Type      Satisfaction
0    Smart Thermostat  Very Unsatisfied
1          Smart Lock           Neutral
2         Smart Light         Satisfied
3    Smart Thermostat    Very Satisfied
4          Smart Lock       Unsatisfied
..                ...               ...
995       Smart Light    Very Satisfied
996  Smart Thermostat    Very Satisfied
997        Smart Lock  Very Unsatisfied
998       Smart Light       Unsatisfied
999  Smart Thermostat           Neutral

[1000 rows x 2 columns]

In [ ]:
# prompt: Using dataframe df1: info

df1.info()


In [22]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Product_Type  1000 non-null   object
 1   Satisfaction  1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB


In [23]:
df1.describe()

Product_Type Satisfaction
count          1000         1000
unique            3            5
top     Smart Light  Unsatisfied
freq            352          212

In [24]:
df1.columns

Index(['Product_Type', 'Satisfaction'], dtype='object')

In [ ]:
# 1. State the Hypotheses:
# H0 (Null Hypothesis): There is no association between product type and customer satisfaction.
# H1 (Alternative Hypothesis): There is a significant association between product type and customer satisfaction.


In [29]:
# 2. Compute the Chi-Square Statistic
# Create a contingency table for Product Type and Satisfaction
contingency_table = pd.crosstab(df1['Product_Type'], df1['Satisfaction'])
contingency_table

Satisfaction      Neutral  Satisfied  Unsatisfied  Very Satisfied  \
Product_Type                                                        
Smart Light            82         56           66              78   
Smart Lock             60         54           60              69   
Smart Thermostat       66         64           86              55   

Satisfaction      Very Unsatisfied  
Product_Type                        
Smart Light                     70  
Smart Lock                      64  
Smart Thermostat                70

In [30]:
# Perform the chi-square test
from scipy.stats import chi2_contingency
chi2, p, dof, expected = chi2_contingency(contingency_table)
chi2, p, dof, expected

(10.776905947426892,
 0.21466323881300367,
 8,
 array([[73.216, 61.248, 74.624, 71.104, 71.808],
        [63.856, 53.418, 65.084, 62.014, 62.628],
        [70.928, 59.334, 72.292, 68.882, 69.564]]))

In [31]:
print(f"Chi-square statistic: {chi2}")
print(f"P-value: {p}")
print(f"Degrees of freedom: {dof}")
print("Expected frequencies:/n", expected)
print(contingency_table)

Chi-square statistic: 10.776905947426892
P-value: 0.21466323881300367
Degrees of freedom: 8
Expected frequencies:/n [[73.216 61.248 74.624 71.104 71.808]
 [63.856 53.418 65.084 62.014 62.628]
 [70.928 59.334 72.292 68.882 69.564]]
Satisfaction      Neutral  Satisfied  Unsatisfied  Very Satisfied  \
Product_Type                                                        
Smart Light            82         56           66              78   
Smart Lock             60         54           60              69   
Smart Thermostat       66         64           86              55   

Satisfaction      Very Unsatisfied  
Product_Type                        
Smart Light                     70  
Smart Lock                      64  
Smart Thermostat                70  
